### ISSUE TITLE
Administrateur front & back

### ISSUE THREAD

**Issue by yassine-berriri** [yassine-berriri/M2MBDS_2023_2024_React_NodeJS_KBBL#2]

**Comment by Ibrahim-krimi** [comment]
Fonctionnalités :
Création de PixelBoard via un formulaire (titre, taille, délai entre deux participations, possibilité de redessiner sur un pixel).
Modification et suppression de PixelBoards.
Affichage, tri et filtrage de tous les PixelBoards.
