### ISSUE TITLE
PixelBoard Front & Back

### ISSUE THREAD

**Issue by yassine-berriri** [yassine-berriri/M2MBDS_2023_2024_React_NodeJS_KBBL#3]

**Comment by Ibrahim-krimi** [comment]
PixelBoard
Objectif : Afficher les détails et permettre l'interaction avec un PixelBoard.
Fonctionnalités :
Affichage des propriétés du PixelBoard (temps restant, titre, taille, délai entre participations, dessin sur pixel existant autorisé ou non). WebSockets : Pour la visualisation en temps réel du dessin.
SuperPixelBoard : Un PixelBoard regroupant toutes les créations.Heatmap : Pour visualiser les zones les plus dessinées.
