### ISSUE TITLE
Utilisateurs Front & Backend

### ISSUE THREAD

**Issue by yassine-berriri** [yassine-berriri/M2MBDS_2023_2024_React_NodeJS_KBBL#5]
Se connecter 
Authentification simple (Basic auth ou jwt) login / mot de passe pour accéder à l'application

**Comment by Ibrahim-krimi** [comment]
Utilisateurs
Objectif : Fournir une expérience utilisateur complète pour les utilisateurs inscrits.
Fonctionnalités :
Connexion via authentification simple (Basic auth ou JWT).
Visualisation et modification du profil et des préférences de thème.
Visualisation des contributions aux PixelBoards et du nombre total de pixels ajoutés.
